### ISSUE TITLE
Just use https for mux lib

### ISSUE THREAD

**Issue by heff** [muxinc/mux-docs#34]
@jsanford8 or @mmcc is there a reason why we wouldn't be able to use https everywhere for the mux javascript lib?

Comment from Scott's implemention.

> I tried the HTML 5 player integration and specified the URL to the Mux JS library exactly as it’s shown in the docs:
> `<script src="//src.litix.io/core/2/mux.js"></script>`

> Using a URI without a protocol (HTTP/HTTPS) led to the URI being treated as a path on the local filesystem. This was clear when I looked at the browser console. I then prefixed the URI with ‘https’, saved the file, refreshed my browser window & played, then the integration was reported was successful.

I run into the same issue every time I do a simple example implementation with people. I brushed it off as a non-typical use case, but it'd be nice if it just wasn't an issue.

**Comment by jsanford8** [comment]
I _think_ we should be able to just use HTTPS, but the idea was to use whatever protocol they were using so we didn't run into things like trying to load HTTP on an HTTPS site. The reverse should be fine (unless there's something weird about iframes?), as far as I know.

**Comment by jsanford8** [comment]
This is done.
